### ISSUE TITLE
MST1.0 TODO 列表

### ISSUE THREAD

**Issue by Windsland52** [Windsland52/MST#7]
- [x] 若邮件不为空，领取后大概率卡死在这里
- [x] 教会补给会漏领一个
- [x] 家园领取凝练石后会因为点击太快卡死
- [x] 上条导致的种植无法正常收获
- [x] 家园派遣会刷掉四星项目
- [x] 拜访好友由于识别太快导致的识别周期很长
- [ ] 巡查中部分选项会卡死
- [x] 公会无法识别签到
- [x] 悬赏未领取
- [x] 领取任务奖励仍有问题
- [x] 菜单选项优化
- [ ] 清体力可选项（主线）
- [x] 自动钓鱼
- [ ] 快速挖矿
- [x] maafw2.0集成实现
- [x] GUI

好多问题啊o(╥﹏╥)o，绝大部分问题都源于截图太快导致的一系列问题，增加判断条件可能是一种解决方案。

**Comment by Windsland52** [comment]
后续打算先研究下python调用接口，然后再修bug。
- [ ] 菜单选项优化
- [ ] 清体力可选项（主线）
其他问题估计没了

**Comment by NEKOice** [comment]
还会继续做吗

**Comment by Windsland52** [comment]
> 还会继续做吗

正在等maafw更新到2.0，会有一些变化

**Comment by NEKOice** [comment]
https://github.com/SweetSmellFox/MFAWPF
有人做了个图形化界面

**Comment by Windsland52** [comment]
> https://github.com/SweetSmellFox/MFAWPF 有人做了个图形化界面

前段时间看到了，正好maafw出2.0了，看看重写集成的时候能不能适配

**Comment by Windsland52** [comment]
2.0重写了一半多了，个人觉得非常稳定，可以把assets文件夹更新为当前main分支的同名文件夹，并将interface.json替换

**Comment by Windsland52** [comment]
gui打算在全部基础功能完成重写后手搓一个，MFA在本人加入custom之前可用
